package effects;

public enum Action {
	EXCHANGE, ASSASSINATE, BLOCKASSASSIN, BLOCKFOREIGNAID, TAX, BLOCKSTEAL, FOREIGNAID, STEAL;

	public static Action[] getActions() {
		return new Action[] { EXCHANGE, ASSASSINATE, BLOCKASSASSIN, BLOCKFOREIGNAID, TAX, BLOCKSTEAL, FOREIGNAID,
				STEAL };
	}
}
